### ISSUE TITLE
ImportError: No module named selenium

### ISSUE THREAD

**Issue by Athyuth** [prykon/GDAT#4]
python gdat.py --url ********.com                                                                          1 ⨯
Traceback (most recent call last):
  File "gdat.py", line 11, in <module>
    from selenium import webdriver
ImportError: No module named selenium

**Comment by prykon** [comment]
Hi Athyuth!
You get that error because Python is trying to use selenium but you don't have that module installed.
Try running `pip install selenium` or `pip3 install selenium`.

Cheers,
